// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYuDOBS37ExyZvWLM9_YGMWzx838_K2ak',
    appId: '1:1063644310518:web:a3e0446293d8121b8975d7',
    messagingSenderId: '1063644310518',
    projectId: 'rentalmanagement-2cb62',
    authDomain: 'rentalmanagement-2cb62.firebaseapp.com',
    databaseURL: 'https://rentalmanagement-2cb62-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rentalmanagement-2cb62.firebasestorage.app',
    measurementId: 'G-FFKFCCHVBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRiuRstYI07n8Put21El6jfJtRxTedJGw',
    appId: '1:1063644310518:android:534c1359f637c8358975d7',
    messagingSenderId: '1063644310518',
    projectId: 'rentalmanagement-2cb62',
    databaseURL: 'https://rentalmanagement-2cb62-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rentalmanagement-2cb62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVv8fZmFvfUAEyjfFocTuh0XwjByOznik',
    appId: '1:1063644310518:ios:04b17f2613a628218975d7',
    messagingSenderId: '1063644310518',
    projectId: 'rentalmanagement-2cb62',
    databaseURL: 'https://rentalmanagement-2cb62-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rentalmanagement-2cb62.firebasestorage.app',
    iosBundleId: 'com.example.unoscore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    databaseURL: 'https://your-project-default-rtdb.firebaseio.com',
    storageBucket: 'your-project.appspot.com',
    iosBundleId: 'com.example.unoScoreTracker',
  );
}